name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # change if your default branch is different
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Build and deploy to Azure Static Web App
      - name: Build and Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"           # skip build, just upload files
          app_location: "/"          # folder containing index.html
          api_location: ""           # leave blank if no API
          output_location: ""        # blank for plain static files
          app_build_command: 'echo "no build"'  # prevents Oryx build errors
